[package]
name = "mdrop"
version = "0.3.0"
authors.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
futures-lite.workspace = true
nusb.workspace = true
tabled.workspace = true
env_logger.workspace = true
log.workspace = true
